### PR TITLE
Minor Bug Fixes & New Icon

### LINKED ISSUE #176: Change DF from 0/1 to T/F

### PR DESCRIPTION
**Pull request by michelleburd**
* Addresses DB change by using true/false with delete flags rather than 1/0
* Fixes some minor UI bugs
* Adds new icon
* Fixes #176

### CODE REVIEW

**Review by blackjack26 — APPROVED** [review]

File: views/account/account_modify.php [hunk 1]
```diff
@@ -191,7 +191,7 @@
 
             if (hasRole(Role::Admin) && $isFacilitator && $setFacilitatorDF == 1) {
                 # Sets DF to 1
-                $db->query("UPDATE facilitators " . " SET df = 1 WHERE facilitatorid = $1", [$employeeid]);
+                $db->query("UPDATE facilitators " . " SET df = TRUE WHERE facilitatorid = $1", [$employeeid]);
```
Comment (ghost) [inline views/account/account_modify.php]: Any reason for the `" . "` in this line or 208?

**Review by ghost — APPROVED** [review]
