### PR TITLE
Fixed reports to work with latest DB

### LINKED ISSUE #117: Update reports to work with latest DB version

### PR DESCRIPTION
**Pull request by stickzman**
Monthly and custom reports will not work without this fix!

Sidenote: Curriculum selection in custom reports works, but it pulls it from the database, so if there is no entries present, there will be nothing to select.

Fixes #117

### CODE REVIEW

File: views/reports/custom_reports_table.php [hunk 1]
```diff
@@ -80,6 +80,19 @@
 	$newRes = pg_fetch_result($db->query($baseQuery . $newWhere, []), 0, 0);
 	$duplRes = $totalRes - $newRes;
 	
+	$currIdSet = "( ";
+	if (count($currs) > 0) {
+		$currIdSet .= $currs[0];
+	}
+	for ($i=1; $i<count($currs); $i++) {
+		$id = $currs[$i];
```
Comment (ghost) [inline views/reports/custom_reports_table.php]: `$id = $currs[$i];` here is unnecessary but gives a bit of self documentation. Instead, add a comment on line 82 explaining what this block of code is doing (getting all of the curricula ids into a comma separated list for pgsql)

**Review by ghost — CHANGES_REQUESTED** [review]

**Review by blackjack26 — APPROVED** [review]

**Review by ghost — APPROVED** [review]
