### PR TITLE
fixing order of first, middle, and last names

### LINKED ISSUE #68: Order of Name Appearance
When doing a live search for a participant, the name shows up as Last, M First as opposed to Last, First M. Doesn't it normally happen that the middle initial is after the first name in other systems?

image

### PR DESCRIPTION
**Pull request by vmjoseph**
Changed order of appearance when user searches for participants
Fixes #68

### CODE REVIEW

File: views/agency-requests/agency_requests_results.php [hunk 1]
```diff
@@ -22,8 +22,8 @@
 $result = $db->query("SELECT  participants.participantid, participants.dateofbirth, participants.race, people.firstname, people.lastname, people.middleinit ".
                         "FROM participants ".
                         "INNER JOIN people ON participants.participantid = people.peopleid ".
-                        "WHERE LOWER(CONCAT(people.firstname, ' ' , people.lastname)) LIKE $1 ".
-                        "OR LOWER(CONCAT(people.lastname, ' ' , people.firstname)) LIKE $1",  ['%'.$searchquery.'%']);
+                        "WHERE LOWER(CONCAT(people.firstname, ' ' , people.middleinit , ' ' , people.lastname)) LIKE $1 ".
```
Comment (blackjack26) [inline views/agency-requests/agency_requests_results.php]: If I had a name like "Johnny M Tester" and I searched "Johnny Tester", according to this nothing would be a match. I think there should be another OR statement that ignores the middle initial as well.

**Review by blackjack26 — CHANGES_REQUESTED** [review]

**Comment by vmjoseph** [comment]
Okay I re-added the previous LIKE statements I had before. Just tested it and it seems to be working as intended.
 ```sql
"SELECT  participants.participantid, participants.dateofbirth, participants.race, people.firstname, people.lastname, people.middleinit ".
                        "FROM participants ".
                        "INNER JOIN people ON participants.participantid = people.peopleid ".
                        "WHERE LOWER(CONCAT(people.firstname, ' ' , people.middleinit , ' ' , people.lastname)) LIKE $1 ".
                        "OR LOWER(CONCAT(people.lastname, ' ' , people.firstname, ' ',people.middleinit )) LIKE $1".
						"OR LOWER(CONCAT(people.firstname, ' ' , people.lastname)) LIKE $1 ".
                        "OR LOWER(CONCAT(people.lastname, ' ' , people.firstname)) LIKE $1",  ['%'.$searchquery.'%'])`

**Review by blackjack26 — APPROVED** [review]
