### PR TITLE
Bug, validation, and UI fixes for the intake packet, referral form, and self-referral form.

### LINKED ISSUE #101: Intake/Referral Validation
Bug fixes for length of phone, last year of school, and zip codes.

Also, removing a participant if the stored procedure fails.

### LINKED ISSUE #106: Referral/Initial Contact Validation
When submitting the referral and initial contact forms with only one of first name or last name, the form will still show that the filled in field is missing.  To clarify, submitting a form with only first name filled in will correctly throw an error because last name is missing, however, it also tells the user that first name, which is filled in, needs to be entered.

### LINKED ISSUE #109: Pop-up for removing
When removing child/party member, a pop-up appears; looks a little weird. 
capture3

### LINKED ISSUE #110: "Remove Member/Party"
If there is only one member of the household or party, should the remove option be displayed? Also, isn't possible to have no household members? Is it possible to accommodate for those situations?

### PR DESCRIPTION
**Pull request by sbohner14335**
Validation for zip code added to ensure user enters a full zip. Modal Created for removing household members/referral parties/children.

Fixes #101 
Fixes #106 
Fixes #109 
Fixes #110

### CODE REVIEW

File: public/js/form_helpers.js [hunk 1]
```diff
@@ -20,42 +20,58 @@ $(document).ready(function(){
...
+    if (reqForm.checkValidity() === false) {
+        card.focus();
+        if(lname.value.length === 0) {
             lname.focus();
-        if(fname.value.length === 0 )
+        }
+        if(fname.value.length === 0 ) {
             fname.focus();
+        }
+    } else if (pers_zip.value.length !== 5 && pers_zip.value.length !== 0) {
```
Comment (evanmena) [inline public/js/form_helpers.js]: Should this be `||` instead of `&&` ?

File: public/js/form_helpers.js [hunk 2]
```diff
@@ -20,42 +20,64 @@ $(document).ready(function(){
...
+    $('.mask-zip')
+        .on('focusout', function() {
+            validateZip($(this));
+        })
 });
 
 function initMask(){
     $('.mask-zip').mask('00000');
-    $('.mask-phone').mask('(000) 000-0000');
+    $('.mask-phone').mask('0000000000');
```
Comment (blackjack26) [inline public/js/form_helpers.js]: Is there a reason this was changed from the `(###) ###-####` format to just numbers?

**Review by blackjack26 — CHANGES_REQUESTED** [review]
With the add and remove buttons I think you should use a font-awesome icon instead of `+` or `-`. I know it wasn't in the issues but it'll make those buttons the same size. You could use:
```html
<span class="fa fa-plus"></span>
```
and
```html
<span class="fa fa-minus"></span>
````

File: public/js/form_helpers.js (hunk 2 above)
Comment (sbohner14335) [reply public/js/form_helpers.js]: The reason I did this was because sometimes the user doesn't provide an area code and the format looks kind of weird in the db. I could easily change it back though if we wanted to say that no area code defaults to the 845 area code. It's really up to you guys.

File: public/js/form_helpers.js [hunk 3]
```diff
@@ -20,42 +20,64 @@ $(document).ready(function(){
...
             fname.focus();
+        } else if (lname.value.length === 0) {
+            card.focus();
+            lname.focus();
+        } else {
+            $('#ref_email').addClass("is-invalid");
+            card2.focus();
+            ref_email.focus();
+        }
+    } else if (pers_zip.value.length !== 5 && pers_zip.value.length !== 0) {
```
Comment (ghost) [inline public/js/form_helpers.js:56]: You already wrote a `validateZip` function, you should change this to `!validZip(pers_zip.value)` . I do see that the `validateZip` function you currently have is also responsible for adding and removing a class to an element, you might write a `validZip` function that checks the length and revise `validateZip` to call` validZip` and then take care of adding/removing classes from the element sent.

**Review by ghost — CHANGES_REQUESTED** [review]

File: public/js/form_helpers.js (hunk 3 above)
Comment (sbohner14335) [reply public/js/form_helpers.js:56]: Done

**Comment by blackjack26** [comment]
@sbohner14335 I squashed the commits on this branch and also changed the phone number formatting back to the `(###) ###-####`. I added a helper function that strips the phone string down to just the numbers. I did notice some issues with the stored procedures and have reported them to the database team. (https://github.com/Capping-CPCA/Database/issues/114, https://github.com/Capping-CPCA/Database/issues/115)

Just so you know, doing `$db->query('...', []);` does not catch errors. You have to catch them yourselves (or look into the database and see that nothing is being inserted).

If you want the updated code on your local, don't pull from the branch do: 

```bash
git fetch -ap
git reset --hard origin/101-intake-referral-validation-fixes
```

**Review by vmjoseph — DISMISSED** [review]
I know this issue is on hold for a little bit, but there are a few validations that are incorrect.
Currently this: 
contactinfo
And this: 
datename
Do not result in an error. I believe the form should handle these in such a way that continuously check the input fields i.e. remove the "Enter first name" when the first name is already entered to reduce user frustration. 
If the address is handling as intended, please disregard

**Comment by sbohner14335** [comment]
Which form is this? I took out the was-validated class so I'm not sure which form you're on

**Comment by vmjoseph** [comment]
@sbohner14335  I believe I was on the ~~intake packet~~ referral packet; The last time I pulled,  which was around yesterday evening, it seemed like there was still something there to cause the validation message.

**Comment by sbohner14335** [comment]
@vmjoseph Which branch are you pulling from? You may not be pulling from 101-intake-referral-validation-fixes, because I just checked and I'm not getting that validation for any of my forms which is the current from 101-intake-referral-validation-fixes.

File: views/forms/form_success.php [hunk 4]
```diff
@@ -37,14 +37,17 @@
                 echo '<div id="referral_submit_success" class="alert alert-success" role="alert">';
                 echo '<h4 class="alert-heading">Success!</h4>';
                 if ($form_type == "agency referral") {
```
Comment (ghost) [inline views/forms/form_success.php]: I think this `if else` section of code has a lot of duplicate code that could be reduced by just inserting `$form_type` into your `echo`s. 

`echo '<p>You have successfully submitted the ' . $form_type . ' form. </p><hr>';`

File: views/forms/referral_form.php [hunk 5]
```diff
@@ -291,11 +291,11 @@
         // agencyMemberInsert for the main agency contact
         $agencyMemberResult = $db->query("SELECT agencyMemberInsert(
                                 agencyMemberID := $1::INT,
-                                agen := $2::referraltype,
-                                phn := $3::text,
-                                em := $4::text,
-                                isMain := $5::boolean,
-                                arID := $6::int
+                                agen := $2::REFERRALTYPE,
+                                phn := $3::INT,
```
Comment (blackjack26) [inline views/forms/referral_form.php]: @sbohner14335 This is the part we are waiting for on the database side. This should be `phn := $3::TEXT` since their procedure had the wrong type. Same with the value on line 329.

**Review by blackjack26 — CHANGES_REQUESTED** [review]

File: views/forms/referral_form.php (hunk 5 above)
Comment (Scott123180) [reply views/forms/referral_form.php]: @blackjack26 
The fontawsome plus and minus sign are being changed in the branch https://github.com/Capping-CPCA/Web-App/tree/103-intake-referral-ui-fixes along with column widths and a few other UI fixes.

**Comment by Scott123180** [comment]
@blackjack26 
The fontawsome plus and minus sign are being changed in the branch https://github.com/Capping-CPCA/Web-App/tree/103-intake-referral-ui-fixes along with column widths and a few other UI fixes.

**Review by blackjack26 — APPROVED** [review]

**Comment by blackjack26** [comment]
I rebased and squashed the commits. Since the DB team added  the fixes for phone numbers I tested that too and it seems to insert into the tables okay.

**Comment by sbohner14335** [comment]
Thanks!

**Comment by sbohner14335** [comment]
@evanmena So I fixed some of the redundant code in my most recent commit. There is still the routing part that is a bit redundant, but it would require either changing the routes (which I can't really do because it would break a lot of stuff), or some other logic that I don't really want to dedicate too much time to as of now.

I can try to cut the code down again after the edit feature is added!

**Comment by blackjack26** [comment]
@sbohner14335 I rebased and squashed onto the current version since I just merged Michelle's stuff

**Review by ghost — APPROVED** [review]
